### PR TITLE
default.yml: Added LittlevGL library as project

### PR DESCRIPTION
**Pull request by vanwinkeljan**
Added LittlevGL (lvgl) GUI library as project

These sources are required for https://github.com/zephyrproject-rtos/zephyr/pull/6826

### CODE REVIEW

**Comment by vanwinkeljan** [comment]
@mbolivar @ulfalizer Is this the intended way of handling external dependencies or is there a different approach?

**Comment by mbolivar** [comment]
This is the idea, yes, but I believe we want to host GitHub forks of each external dependency in our mainline manifest, so that everything uses GitHub.com/zephyrproject-rtos/REPO_NAME URLs, rather than pointing at the upstreams themselves (as they may change unexpectedly).
@carlescufi is that your expectation as well?

**Comment by carlescufi** [comment]
> This is the idea, yes, but I believe we want to host GitHub forks of each external dependency in our mainline manifest, so that everything uses GitHub.com/zephyrproject-rtos/REPO_NAME URLs, rather than pointing at the upstreams themselves (as they may change unexpectedly).
> @carlescufi is that your expectation as well?

It is indeed. We want to protect ourselves from projects disappearing, so we want to host a mirror.

**Comment by vanwinkeljan** [comment]
> It is indeed. We want to protect ourselves from projects disappearing, so we want to host a mirror.

Ok totally understandable but who can create this mirror?

**Comment by carlescufi** [comment]
> > It is indeed. We want to protect ourselves from projects disappearing, so we want to host a mirror.
> 
> Ok totally understandable but who can create this mirror?

Myself or @nashif can. That said, we might want to defer merging this PR until west is actually in the hands of users with the default manifest pointing to a single repo (zephyr) first.

**Comment by vanwinkeljan** [comment]
sources are included in zephyr repo for now

**Pull request closed without merging**
